### Ejercicio 1.6 David Garcia - Generando números binarios
Una función recursiva que genera e imprime todos los números binarios de ``n`` dígitos se puede plantear con un encabezado de la siguiente manera:

In [ ]:
def genera_binarios(a,k,n):
  #Aquí debes definir tu código

  if k==n:
    print(a) #Se imprime el arreglo a con sus digitos formando el numero binario
  else:
    a[k]=0 #0 en la posición actual
    genera_binarios(a,k+1,n) #Debemos mover el programa con el grado de avance k, también para no caer en una recursión infinita
    a[k]=1 #Se reemplaza el 0 de la posicion anterior por 1
    genera_binarios(a,k+1,n) #Se vuelve a llamar recursivamente aumentando de nuevo el k para avanzar

    #Tarde más de lo recomendado tratando de entender como funciona el algoritmo y lo que me paso, es que el algoritmo que nos propone:
    #dice reemplazar el 0 anterior por 1 un en la "misma k-esima posición", yo por esto entiendo que al k-1 se le debe asignar 1 justo después de aumentar el k
    #para respetar la anterior misma k-esima posición, pero esto mismo genera que no funcione correctamente la generación de numeros binarios.
    #genera_binarios(a,k+1,n)
    #a[k-1]=1
    #genera_binarios(a,k+1,n)

    #Finalmente la versión de arriba sin comentar resuelve correctamente el problema con recursión


Donde ``a`` es un arreglo que contiene los unos y ceros de los números que se van generando, el cual se va rellenando con valores de izquierda a derecha, ``k`` es el grado de avance en el proceso de generación (más precisamente cuantos dígitos se han generado hasta esta llamada) y ``n`` es la cantidad total de dígitos que deben generarse (``n = len(a)``). Por lo tanto ``n-k`` es la cantidad de dígitos que faltan por generar. Esta función se llama la primera vez de la siguiente manera:

In [ ]:
import numpy as np
n = 4
a = np.empty(n,dtype=int) # arreglo de largo n sin inicializar
genera_binarios(a,0,len(a))

[0 0 0 0]
[0 0 0 1]
[0 0 1 0]
[0 0 1 1]
[0 1 0 0]
[0 1 0 1]
[0 1 1 0]
[0 1 1 1]
[1 0 0 0]
[1 0 0 1]
[1 0 1 0]
[1 0 1 1]
[1 1 0 0]
[1 1 0 1]
[1 1 1 0]
[1 1 1 1]


Este código debe generar la salida:

[0 0 0 0]

[0 0 0 1]

[0 0 1 0]

[0 0 1 1]

[0 1 0 0]

[0 1 0 1]

[0 1 1 0]

[0 1 1 1]

[1 0 0 0]

[1 0 0 1]

[1 0 1 0]

[1 0 1 1]

[1 1 0 0]

[1 1 0 1]

[1 1 1 0]

[1 1 1 1]

Se le pide que escriba las instrucciones de la función ``genera_binarios`` de acuerdo al siguiente algoritmo:

---



* si el valor de ``k`` es igual a ``n``, ya se han generado todos los dígitos por
    lo cual se imprime el arreglo en pantalla ``(print(a))``
* si no, se hacen dos cosas:  
    - se pone un 0 en la ``k``-ésima posicion y se llama recursivamente
      a la función para que genere los dígitos restantes
    - luego se pone un 1 en la misma ``k``-ésima posición (reemplazando el 0) y se
      llama recursivamente a la función para que genere los dígitos restantes

Pruebe su función con para el caso ``n=4``. Asegúrese de que genere el mismo resultado que el que aparece en el enunciado.
